/* Generated by CLooG v0.12.1 in 0.26s. */
for (i=m;i<=min(min(n,p-1),q);i++) {
  S1 ;
}
for (i=p;i<=min(min(q,m-1),n);i++) {
  S2 ;
}
for (i=max(m,p);i<=min(n,q);i++) {
  S1 ;
  S2 ;
}
for (i=max(m,q+1);i<=n;i++) {
  S1 ;
}
for (i=max(p,n+1);i<=q;i++) {
  S2 ;
}
