/* Generated by CLooG v0.10.7 */
for (i=0;i<=14;i++) {
  for (j=0;j<=n-15;j++) {
    S1 ;
  }
}
for (i=15;i<=n;i++) {
  for (j=0;j<=9;j++) {
    S1 ;
  }
  for (j=10;j<=n-15;j++) {
    S1 ;
    S2 ;
  }
  for (j=n-14;j<=n;j++) {
    S2 ;
  }
}
