/* Generated by CLooG v0.10.7 */
for (c1=1;c1<=N;c1++) {
  S1(i = c1) ;
}
for (c1=N+1;c1<=2*N;c1++) {
  for (i=1;i<=N;i++) {
    j = c1-N ;
    S2 ;
  }
}
for (c1=2*N+1;c1<=M+N;c1++) {
  for (i=1;i<=N;i++) {
    j = c1-2*N ;
    S3 ;
    j = c1-N ;
    S2 ;
  }
}
for (c1=M+N+1;c1<=M+2*N;c1++) {
  for (i=1;i<=N;i++) {
    j = c1-2*N ;
    S3 ;
  }
}
