/* Generated by CLooG v0.10.7 */
for (c1=M+1;c1<=2*M;c1++) {
  i = c1-M ;
  S1 ;
}
for (c1=2*M+1;c1<=M+N;c1++) {
  i = c1-2*M ;
  S2 ;
  i = c1-M ;
  S1 ;
}
for (c1=M+N+1;c1<=2*M+N;c1++) {
  i = c1-2*M ;
  S2 ;
}
