/* Generated by CLooG v0.10.7 */
for (i=1;i<=M-3;i++) {
  for (j=1;j<=i+1;j++) {
    S1 ;
  }
  j = i+2 ;
  S1 ;
  S2 ;
  for (j=i+3;j<=M;j++) {
    S1 ;
  }
}
if (M >= 3) {
  i = M-2 ;
  for (j=1;j<=M-1;j++) {
    S1 ;
  }
  S1(j = M) ;
  S2(j = M) ;
}
for (i=M-1;i<=M;i++) {
  for (j=1;j<=M;j++) {
    S1 ;
  }
  j = i+2 ;
  S2 ;
}
