/* Generated by CLooG v0.10.7 */
for (j=0;j<=7;j++) {
  S1(i = 1) ;
}
for (i=2;i<=5;i++) {
  for (j=0;j<=i-2;j++) {
    S2 ;
  }
  for (j=i-1;j<=4;j++) {
    S1 ;
    S2 ;
  }
  for (j=5;j<=7;j++) {
    S1 ;
  }
}
for (j=0;j<=4;j++) {
  S2(i = 6) ;
}
for (j=5;j<=7;j++) {
  S1(i = 6) ;
}
for (i=7;i<=8;i++) {
  for (j=i-1;j<=7;j++) {
    S1 ;
  }
}
