/* Generated by CLooG v0.10.7 */
if (n >= 2) {
  for (j=2;j<=n;j++) {
    S1(i = 1) ;
  }
}
for (c1=2;c1<=n-1;c1++) {
  for (c2=2;c2<=n-1;c2++) {
    for (i=1;i<=min(c2-1,c1-1);i++) {
      S2(j = c2,k = c1) ;
    }
  }
  for (i=1;i<=c1-1;i++) {
    S2(j = n,k = c1) ;
  }
  for (j=c1+1;j<=n;j++) {
    S1(i = c1) ;
  }
}
if (n >= 2) {
  for (c2=2;c2<=n;c2++) {
    for (i=1;i<=c2-1;i++) {
      S2(j = c2,k = n) ;
    }
  }
}
