/* Generated by CLooG v0.10.7 */
if (M >= 2) {
  for (l=2;l<=M;l++) {
    S1(i = 1,j = 1,k = M) ;
  }
}
for (i=2;i<=M-1;i++) {
  for (j=1;j<=i-1;j++) {
    for (k=j+1;k<=M;k++) {
      S2(l = k,m = i) ;
    }
  }
  for (l=i+1;l<=M;l++) {
    S1(j = i,k = M) ;
  }
}
if (M >= 2) {
  for (j=1;j<=M-1;j++) {
    for (k=j+1;k<=M;k++) {
      S2(i = M,l = k,m = M) ;
    }
  }
}
