/* Generated by CLooG v0.10.7 */
for (i=0;i<=N;i++) {
  for (j=0;j<=i;j++) {
    S1 ;
    S2 ;
  }
}
for (i=N+1;i<=M;i++) {
  for (j=0;j<=N;j++) {
    S1 ;
    S2 ;
  }
  for (j=N+1;j<=i;j++) {
    S1 ;
  }
}
