/* Generated by CLooG v0.10.7 */
if (n >= 2) {
  for (j=2;j<=n;j++) {
    S1(i = 1) ;
  }
}
for (proc=2;proc<=n-1;proc++) {
  for (i=1;i<=proc-1;i++) {
    for (j=i+1;j<=n;j++) {
      S2(k = proc) ;
    }
  }
  for (j=proc+1;j<=n;j++) {
    S1(i = proc) ;
  }
}
if (n >= 2) {
  for (i=1;i<=n-1;i++) {
    for (j=i+1;j<=n;j++) {
      S2(k = n) ;
    }
  }
}
