/* Generated by CLooG v0.10.7 */
for (i=0;i<=3;i++) {
  S1(j = i) ;
  S2(j = i) ;
  for (j=i+1;j<=4;j++) {
    S2 ;
  }
  S2(j = 5) ;
  S3(j = 5) ;
}
S1(i = 4,j = 4) ;
S2(i = 4,j = 4) ;
S2(i = 4,j = 5) ;
S3(i = 4,j = 5) ;
S1(i = 5,j = 5) ;
S2(i = 5,j = 5) ;
S3(i = 5,j = 5) ;
